apiVersion: v1
kind: Pod
metadata:
  name: pod-nandu-pvc1
  labels:
    app: nginx
spec:
  containers:
  - name: app-container
    image: nginx:latest
    volumeMounts:
    - name: pvc-volume
      mountPath: /usr/share/nginx/html  # Path inside the container
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: my-nandu-pvc  # Name of the PVC

