apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nandu-pv
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual  
  hostPath:
    path: /mnt/data  
    type: DirectoryOrCreate


