apiVersion: v1
kind: Service
metadata:
  name: my-servicee-nodeport1
spec:
  selector:
    app: nginx  # This should match the label of your pod
  ports:
    - protocol: TCP
      port: 80        # Port exposed by the service
      targetPort: 80   # Port inside the container
      nodePort: 31183  # The external port on the node
  type: NodePort      # Set type to NodePort to expose service externally

